version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[API]"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"