name: Build ktor server template
run-name: ${{ github.actor }} is executing GitHub Actions 🚀
on: [push, pull_request]

jobs:
  build:
    name: Build ktor server API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Gradle cache and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: 🏗 Build with Gradle 🛠️
        run: ./gradlew build --stacktrace